--- 
title: "Socioeconomic Discussion on Rural Atlas data"
author: "Ivy Liu(wl2773) & Changhao He(ch3557) & Yiling Tian(yt2746)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Rural area residents whose population is 14 percent of the US residents (based on results from July 2017) spread across 72 percent of Nation’s land area, but do we know enough about Rural areas other than this fact? What kind of image comes to mind when thinking of a rural place? Does it include the farmhouse down the road? Does it include communities stand at the crossroads? Does it include housing division next to a farmed land? The answers to the previous questions might be ‘Yes’, but to better understand the social and economic status of the rural areas and small towns in the US, we need more analyses.\

Over the past century, the US has experienced a significant urban growth. With the expansion of urban areas and urban population, the rural population growth rate has declined over the decades. In 2010, the US rural population growth rate has reversed for the first time. In 2016-2017, the rural population increased by 0.1 percentage and this rather modest increases continues. However, the US population in rural counties stood at 46.1 million in July 2019, which essentially stay unchanged from 46.2 million in 2010. Without a doubt, the stability in the small town population growth rate does not indicate all the socioeconomic indicators stay unchanged across all the counties. Therefore, in this project, we are trying to discuss some interesting social aspects of the US counties through geographic, time series and dependency relationship analysis. Specifically, we are trying to describe the socioeconomic status variation across different parts of the US rural areas; unemployment rate changes from 2009 to 2019 across different regions of the Nation's land , and possible dependency relationships between socioeconomic factors we focus on.  \


## Reference:\
1. Info about rural population proportion and living space spread:\
https://www.ers.usda.gov/topics/rural-economy-population/population-migration.aspx

2. Info about rural population changes from 2010 to 2019:\
https://www.ers.usda.gov/amber-waves/2019/february/rural-population-trends/
